// Networking page styles (My Network tree + My Referrals table)
const networkingStyles = {
    // My Network page
    networkContainer: {
        width: '100%',
        minHeight: '100%',
    },
    networkTitle: {
        fontSize: '24px',
        fontWeight: 'bold',
        color: '#fff',
        marginBottom: '8px',
    },
    networkDivider: {
        height: '2px',
        background: 'linear-gradient(to right, #dc2626, transparent)',
        marginBottom: '24px',
    },
    networkZoomControls: {
        display: 'flex',
        justifyContent: 'center',
        gap: '24px',
        marginBottom: '24px',
    },
    networkZoomBtn: {
        background: 'transparent',
        border: 'none',
        color: '#60a5fa',
        fontSize: '15px',
        cursor: 'pointer',
        display: 'flex',
        alignItems: 'center',
        padding: '8px 16px',
        borderRadius: '8px',
        transition: 'background 0.2s',
    },
    networkTreeWrapper: {
        overflow: 'auto',
        padding: '24px',
        minHeight: '400px',
        display: 'flex',
        justifyContent: 'center',
    },
    networkLoading: {
        textAlign: 'center',
        color: '#9ca3af',
        padding: '60px 0',
    },
    networkNoData: {
        textAlign: 'center',
        color: '#6b7280',
        padding: '60px 0',
        fontSize: '16px',
    },

    // Tree node styles
    treeNodeContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        position: 'relative',
    },
    treeNodeWrapper: {
        display: 'flex',
        justifyContent: 'center',
    },
    treeNode: {
        background: '#16a34a',
        color: '#fff',
        padding: '10px 20px',
        borderRadius: '8px',
        fontSize: '13px',
        fontWeight: '600',
        textAlign: 'center',
        whiteSpace: 'nowrap',
        boxShadow: '0 4px 12px rgba(22, 163, 74, 0.3)',
        transition: 'transform 0.15s, box-shadow 0.15s',
        display: 'flex',
        flexDirection: 'column',
        gap: '2px',
        minWidth: '100px',
    },
    treeNodeRoot: {
        boxShadow: '0 4px 20px rgba(22, 163, 74, 0.5)',
        padding: '12px 24px',
        fontSize: '14px',
    },
    treeNodeInactive: {
        background: '#dc2626',
        boxShadow: '0 4px 12px rgba(220, 38, 38, 0.3)',
    },
    treeNodeRootInactive: {
        boxShadow: '0 4px 20px rgba(220, 38, 38, 0.5)',
    },
    treeNodeCode: {
        fontFamily: 'monospace',
        letterSpacing: '0.5px',
    },
    treeNodeName: {
        fontSize: '11px',
        opacity: 0.85,
        fontWeight: '400',
    },
    treeChildrenContainer: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },
    treeLine: {
        width: '2px',
        height: '24px',
        background: '#4b5563',
    },
    treeChildrenRow: {
        display: 'flex',
        gap: '24px',
        justifyContent: 'center',
    },
    treeChildBranch: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
    },

    // My Referrals page
    referralsContainer: {
        width: '100%',
    },
    referralsTitle: {
        fontSize: '24px',
        fontWeight: 'bold',
        color: '#fff',
        marginBottom: '8px',
    },
    referralsDivider: {
        height: '2px',
        background: 'linear-gradient(to right, #dc2626, transparent)',
        marginBottom: '24px',
    },
    referralsToolbar: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: '16px',
        flexWrap: 'wrap',
        gap: '12px',
    },
    referralsSearchBox: {
        display: 'flex',
        alignItems: 'center',
        background: '#1a1a1a',
        border: '1px solid #333',
        borderRadius: '8px',
        padding: '8px 12px',
        minWidth: '200px',
    },
    referralsSearchIcon: {
        width: '18px',
        height: '18px',
        color: '#6b7280',
        marginRight: '8px',
        flexShrink: 0,
    },
    referralsSearchInput: {
        background: 'transparent',
        border: 'none',
        color: '#fff',
        outline: 'none',
        fontSize: '14px',
        width: '100%',
    },
    referralsToolbarRight: {
        display: 'flex',
        gap: '8px',
    },
    referralsDateBtn: {
        display: 'flex',
        alignItems: 'center',
        background: '#1e3a5f',
        color: '#fff',
        border: 'none',
        borderRadius: '8px',
        padding: '10px 16px',
        fontSize: '13px',
        fontWeight: '600',
        cursor: 'pointer',
    },
    referralsFilterBtn: {
        display: 'flex',
        alignItems: 'center',
        background: '#5b1a1a',
        color: '#fff',
        border: 'none',
        borderRadius: '8px',
        padding: '10px 16px',
        fontSize: '13px',
        fontWeight: '600',
        cursor: 'pointer',
    },
    referralsDateFilterRow: {
        display: 'flex',
        alignItems: 'center',
        gap: '12px',
        marginBottom: '16px',
        flexWrap: 'wrap',
    },
    referralsDateInput: {
        background: '#1a1a1a',
        border: '1px solid #333',
        color: '#fff',
        borderRadius: '6px',
        padding: '8px 12px',
        fontSize: '13px',
        outline: 'none',
    },
    referralsApplyBtn: {
        background: '#1e3a5f',
        color: '#fff',
        border: 'none',
        borderRadius: '6px',
        padding: '8px 16px',
        fontSize: '13px',
        cursor: 'pointer',
    },
    referralsClearBtn: {
        background: '#333',
        color: '#fff',
        border: 'none',
        borderRadius: '6px',
        padding: '8px 16px',
        fontSize: '13px',
        cursor: 'pointer',
    },
    referralsTableWrapper: {
        overflowX: 'auto',
        borderRadius: '8px',
        border: '1px solid #333',
    },
    referralsTable: {
        width: '100%',
        borderCollapse: 'collapse',
    },
    referralsTh: {
        background: '#7f1d1d',
        color: '#fff',
        padding: '12px 16px',
        textAlign: 'left',
        fontSize: '13px',
        fontWeight: '600',
        whiteSpace: 'nowrap',
    },
    referralsTd: {
        padding: '12px 16px',
        fontSize: '13px',
        borderBottom: '1px solid #222',
        whiteSpace: 'nowrap',
    },
    referralsRowEven: {
        background: '#f5f5f5',
        color: '#111',
    },
    referralsRowOdd: {
        background: '#e5e5e5',
        color: '#111',
    },
    referralsEmptyCell: {
        padding: '16px',
        color: '#6b7280',
        fontSize: '14px',
        background: '#f5f5f5',
    },
    referralsPagination: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: '16px',
        paddingTop: '16px',
        borderTop: '1px solid #222',
    },
    referralsPaginationLeft: {
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
    },
    referralsRowsSelect: {
        background: '#1a1a1a',
        border: '1px solid #333',
        color: '#fff',
        borderRadius: '4px',
        padding: '4px 8px',
        fontSize: '13px',
        outline: 'none',
    },
    referralsPaginationRight: {
        display: 'flex',
        gap: '8px',
    },
    referralsPageBtn: {
        background: '#5b1a1a',
        color: '#fff',
        border: 'none',
        borderRadius: '6px',
        padding: '8px 16px',
        fontSize: '13px',
        fontWeight: '600',
        cursor: 'pointer',
    },
};

export default networkingStyles;
