import React, { useState, useEffect } from 'react';
import api from '../services/api';
import PageHeader from '../components/common/PageHeader';
import { networkingStyles as ns } from '../styles';

const LevelEarnings = () => {
    const [earnings, setEarnings] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchEarnings = async () => {
            try {
                const data = await api.get('/api/user/level-earnings');
                setEarnings(data);
            } catch (err) {
                console.error('Failed to fetch level earnings', err);
            } finally {
                setLoading(false);
            }
        };
        fetchEarnings();
    }, []);

    const levels = Array.from({ length: 8 }, (_, i) => `Level ${i + 1}`);

    if (loading) {
        return (
            <div style={ns.networkContainer}>
                <PageHeader title="Level Earnings" />
                <div style={ns.networkLoading}>Loading earnings...</div>
            </div>
        );
    }

    return (
        <div style={ns.networkContainer}>
            <PageHeader title="Level Earnings" />
            
            <div style={{
                display: 'grid',
                gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
                gap: '20px',
                marginTop: '20px'
            }}>
                {levels.map((level) => (
                    <div key={level} style={{
                        background: 'rgba(255, 255, 255, 0.03)',
                        backdropFilter: 'blur(10px)',
                        border: '1px solid rgba(255, 255, 255, 0.1)',
                        borderRadius: '16px',
                        padding: '24px',
                        display: 'flex',
                        flexDirection: 'column',
                        justifyContent: 'space-between',
                        transition: 'transform 0.3s ease, border-color 0.3s ease',
                        cursor: 'default',
                    }}
                    onMouseEnter={(e) => {
                        e.currentTarget.style.transform = 'translateY(-5px)';
                        e.currentTarget.style.borderColor = 'rgba(167, 139, 250, 0.4)';
                    }}
                    onMouseLeave={(e) => {
                        e.currentTarget.style.transform = 'translateY(0)';
                        e.currentTarget.style.borderColor = 'rgba(255, 255, 255, 0.1)';
                    }}
                    >
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
                            <span style={{ fontSize: '14px', color: '#94a3b8', fontWeight: '500' }}>{level}</span>
                            <div style={{ 
                                width: '32px', 
                                height: '32px', 
                                borderRadius: '8px', 
                                background: 'rgba(167, 139, 250, 0.1)', 
                                display: 'flex', 
                                justifyContent: 'center', 
                                alignItems: 'center' 
                            }}>
                                <svg className="w-4 h-4 text-purple-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6"></path>
                                </svg>
                            </div>
                        </div>
                        <div>
                            <span style={{ fontSize: '28px', fontWeight: '700', color: '#fff' }}>
                                ₹{earnings?.[level]?.toLocaleString() || '0.00'}
                            </span>
                            <p style={{ fontSize: '12px', color: '#64748b', marginTop: '4px' }}>Total Cumulative Earnings</p>
                        </div>
                    </div>
                ))}
            </div>

            <div style={{
                marginTop: '40px',
                padding: '24px',
                background: 'rgba(167, 139, 250, 0.05)',
                borderRadius: '16px',
                border: '1px dashed rgba(167, 139, 250, 0.2)'
            }}>
                <h3 style={{ color: '#a78bfa', fontSize: '18px', fontWeight: '600', marginBottom: '8px' }}>Earning Insights</h3>
                <p style={{ color: '#94a3b8', fontSize: '14px', lineHeight: '1.6' }}>
                    This dashboard provides a breakdown of your earnings across 8 levels of your referral network. 
                    Level 1 includes your direct referrals, while Levels 2-8 represent the downline generated by your network.
                    Earnings are credited automatically based on the active plans within your organization.
                </p>
            </div>
        </div>
    );
};

export default LevelEarnings;
