import React, { useState, useEffect } from 'react';
import api from '../services/api';
import PageHeader from '../components/common/PageHeader';
import { networkingStyles as ns, transactionsStyles as ts } from '../styles';
import { ChevronDown, ChevronUp, Users, DollarSign, Briefcase, TrendingUp } from 'lucide-react';

const LevelEarnings = () => {
    const [breakdown, setBreakdown] = useState(null);
    const [loading, setLoading] = useState(true);
    const [expandedLevel, setExpandedLevel] = useState(1);

    useEffect(() => {
        const fetchBreakdown = async () => {
            try {
                const data = await api.get('/api/user/level-earnings');
                setBreakdown(data);
            } catch (err) {
                console.error('Failed to fetch level breakdown', err);
            } finally {
                setLoading(false);
            }
        };
        fetchBreakdown();
    }, []);

    const toggleLevel = (level) => {
        setExpandedLevel(expandedLevel === level ? null : level);
    };

    const calculateGrandTotal = () => {
        if (!breakdown) return 0;
        return Object.values(breakdown).reduce((sum, levelData) => sum + (levelData.subtotals?.earnings || 0), 0);
    };

    if (loading) {
        return (
            <div style={ns.networkContainer}>
                <PageHeader title="Level Earnings Breakdown" />
                <div style={ns.networkLoading}>Loading detailed breakdown...</div>
            </div>
        );
    }

    return (
        <div style={ns.networkContainer}>
            <PageHeader title="Level Earnings Breakdown" />

            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center" style={{
                marginTop: '24px',
                padding: '24px',
                background: 'linear-gradient(135deg, rgba(16, 185, 129, 0.1) 0%, rgba(16, 185, 129, 0.05) 100%)',
                borderRadius: '16px',
                border: '1px solid rgba(16, 185, 129, 0.2)',
                gap: '16px'
            }}>
                <div>
                    <h3 style={{ color: '#10b981', fontSize: '18px', fontWeight: '600', marginBottom: '4px' }}>Total Level Income (All-Time)</h3>
                    <p style={{ color: '#94a3b8', fontSize: '14px' }}>This sum matches your Level Wallet Balance</p>
                </div>
                <div style={{ fontSize: '32px', fontWeight: 'bold', color: '#10b981' }}>
                    ${calculateGrandTotal().toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                </div>
            </div>

            <div style={{ display: 'flex', flexDirection: 'column', gap: '16px', marginTop: '24px' }}>
                {Object.keys(breakdown || {}).map((level) => (
                    <LevelAccordion
                        key={level}
                        level={level}
                        data={breakdown[level]}
                        isOpen={expandedLevel === parseInt(level)}
                        onToggle={() => toggleLevel(parseInt(level))}
                    />
                ))}
            </div>

            <div style={{
                marginTop: '40px',
                padding: '24px',
                background: 'rgba(167, 139, 250, 0.05)',
                borderRadius: '16px',
                border: '1px dashed rgba(167, 139, 250, 0.2)'
            }}>
                <h3 style={{ color: '#a78bfa', fontSize: '18px', fontWeight: '600', marginBottom: '8px' }}>Understanding Your Network</h3>
                <p style={{ color: '#94a3b8', fontSize: '14px', lineHeight: '1.6' }}>
                    <strong>Deposit Amount:</strong> The total primary investment made by each person at this level.<br />
                    <strong>Total Business:</strong> The cumulative business volume generated by a person, including their own deposit and all deposits from their entire downline.<br />
                    <strong>Earnings:</strong> The total commission and bonuses you have earned from this specific member's activity.
                </p>
            </div>
        </div>
    );
};

const LevelAccordion = ({ level, data, isOpen, onToggle }) => {
    const { members, subtotals } = data;

    return (
        <div style={{
            background: 'rgba(255, 255, 255, 0.02)',
            border: '1px solid rgba(255, 255, 255, 0.1)',
            borderRadius: '12px',
            overflow: 'hidden',
            transition: 'all 0.3s ease'
        }}>
            {/* Header */}
            <div
                onClick={onToggle}
                style={{
                    padding: '20px 24px',
                    display: 'flex',
                    justifyContent: 'space-between',
                    alignItems: 'center',
                    cursor: 'pointer',
                    background: isOpen ? 'rgba(167, 139, 250, 0.05)' : 'transparent',
                    borderBottom: isOpen ? '1px solid rgba(255, 255, 255, 0.1)' : 'none'
                }}
            >
                <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
                    <div style={{
                        width: '40px',
                        height: '40px',
                        borderRadius: '10px',
                        background: 'rgba(167, 139, 250, 0.1)',
                        display: 'flex',
                        justifyContent: 'center',
                        alignItems: 'center',
                        color: '#a78bfa'
                    }}>
                        <TrendingUp size={20} />
                    </div>
                    <div>
                        <h4 style={{ color: '#fff', fontSize: '16px', fontWeight: '600' }}>Level {level}</h4>
                        <span style={{ color: '#64748b', fontSize: '12px' }}>{members.length} Members</span>
                    </div>
                </div>

                <div style={{ display: 'flex', gap: '32px', alignItems: 'center' }}>
                    <div className="hidden md:flex flex-col items-end">
                        <span style={{ color: '#64748b', fontSize: '10px', textTransform: 'uppercase' }}>Level Earnings</span>
                        <span style={{ color: '#10b981', fontWeight: '700' }}>${subtotals.earnings.toLocaleString()}</span>
                    </div>
                    {isOpen ? <ChevronUp size={20} color="#64748b" /> : <ChevronDown size={20} color="#64748b" />}
                </div>
            </div>

            {/* Content */}
            {isOpen && (
                <div style={{ padding: '0px' }}>
                    <div className={ts.transactionTableWrapper} style={{ border: 'none', borderRadius: '0' }}>
                        <table className={ts.transactionTable}>
                            <thead className={ts.transactionThead} style={{ background: 'rgba(255, 255, 255, 0.03)' }}>
                                <tr>
                                    <th className={ts.transactionTh}>Name / Code</th>
                                    <th className={ts.transactionTh}>Deposit</th>
                                    <th className={ts.transactionTh}>Total Business</th>
                                    <th className={ts.transactionTh}>Your Earning</th>
                                </tr>
                            </thead>
                            <tbody>
                                {members.length === 0 ? (
                                    <tr>
                                        <td colSpan="4" className={ts.transactionNoData}>No members found at this level</td>
                                    </tr>
                                ) : (
                                    members.map((member, idx) => (
                                        <tr key={idx} className={ts.transactionTr}>
                                            <td className={ts.transactionTdBold}>
                                                <div style={{ display: 'flex', flexDirection: 'column' }}>
                                                    <span>{member.name}</span>
                                                    <span style={{ fontSize: '10px', color: '#64748b', fontWeight: 'normal' }}>{member.referralCode}</span>
                                                </div>
                                            </td>
                                            <td className={ts.transactionTd}>${member.deposit.toLocaleString()}</td>
                                            <td className={ts.transactionTd}>
                                                <span style={{ color: '#a78bfa', fontWeight: '500' }}>${member.business.toLocaleString()}</span>
                                            </td>
                                            <td className={ts.transactionTd}>
                                                <span style={{ color: '#10b981', fontWeight: '600' }}>${member.earnings.toLocaleString()}</span>
                                            </td>
                                        </tr>
                                    ))
                                )}
                            </tbody>
                            {members.length > 0 && (
                                <tfoot style={{ background: 'rgba(167, 139, 250, 0.03)', borderTop: '2px solid rgba(255, 255, 255, 0.1)' }}>
                                    <tr>
                                        <td className={ts.transactionTdBold} style={{ color: '#a78bfa' }}>LEVEL {level} TOTAL</td>
                                        <td className={ts.transactionTdBold}>${subtotals.deposit.toLocaleString()}</td>
                                        <td className={ts.transactionTdBold} style={{ color: '#a78bfa' }}>${subtotals.business.toLocaleString()}</td>
                                        <td className={ts.transactionTdBold} style={{ color: '#10b981' }}>${subtotals.earnings.toLocaleString()}</td>
                                    </tr>
                                </tfoot>
                            )}
                        </table>
                    </div>
                </div>
            )}
        </div>
    );
};

export default LevelEarnings;
